apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interactive-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ug-devops/interactive-app'  # Your GitHub repo
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

